Category
WildCodeSchool/goodealmaps pull request #12
Opened 2022-11-03 11:45 UTC by Kengaroo

Page for displaying announcement; navbar to chose category (All/Resto/Accomodation/Events); region filter;

2022-11-03 13:35 UTC, cruiser22 approved these changes
ok

2022-11-03 15:12 UTC, Benja-san requested changes

2022-11-03 15:12 UTC, Benja-san commented on public/assets/css/announcement.css
> +:root {
global behavior must be in global css file

2022-11-03 15:12 UTC, Benja-san commented on public/assets/css/announcement.css
> +nav {
use className instead of tag otherwise all nav tags will take this behavior

2022-11-03 15:12 UTC, Benja-san commented on src/Model/AnnouncementManager.php
> +     * Update announsment in database
grammatical error

2022-11-03 15:12 UTC, Benja-san commented on src/Model/AnnouncementManager.php
> +     * Update announsment in database
grammatical error

2022-11-03 15:12 UTC, Benja-san commented on src/View/Announcement/index.html.twig
> +<div>
please use main tag

2022-11-03 15:12 UTC, Benja-san commented on src/View/Announcement/index.html.twig
> +    <div class="container">
since you'll get a list of announcments, please use a ul tag and wrap your card inclusion inside a li tag

2022-11-03 15:12 UTC, Benja-san commented on src/View/Announcement/index.html.twig
> +            <p>Rien trouvé, désolé</p>
wrap this p tag inside li tag

2022-11-04 09:42 UTC, Benja-san approved these changes

2022-11-04 09:47 UTC, merged