About us
WildCodeSchool/goodealmaps pull request #13
Opened 2022-11-03 13:03 UTC by Kengaroo

About Us page (merged with dev)

2022-11-03 13:38 UTC, cruiser22 approved these changes
ok

2022-11-03 15:16 UTC, Benja-san requested changes

2022-11-03 15:16 UTC, Benja-san commented on src/View/about/about.html.twig
>  	<h1>Qui nous sommes </h1>
please wrap everything inside a main tag

2022-11-03 15:16 UTC, Benja-san commented on src/View/about/about.html.twig
> +    <h3>Salut !</h3>
where is the h2 ?

2022-11-04 11:35 UTC, Benja-san requested changes

2022-11-04 11:35 UTC, Benja-san commented on src/View/about/about.html.twig
> +	<h1 class="about">Qui nous sommes </h1>
h1 must be inside main tag

2022-11-04 11:35 UTC, Benja-san commented on src/View/layout.html.twig
> +    	{% include 'Components/_header.html.twig' %}
if your header and footer is available in all pages, you should put it ahead of header / footer block

2022-11-04 12:23 UTC, Benja-san approved these changes

2022-11-04 12:27 UTC, merged