Form add goodeal
WildCodeSchool/goodealmaps pull request #18
Opened 2022-11-07 15:01 UTC by cruiser22

Form to add our "good deal"

2022-11-07 15:15 UTC, AlexMouth approved these changes

2022-11-09 10:56 UTC, Benja-san requested changes

2022-11-09 10:56 UTC, Benja-san commented on src/Controller/AnnouncementController.php
> +       /* $announcementManager = new AnnouncementManager();
kill dead code please

2022-11-09 10:56 UTC, Benja-san commented on src/Controller/FormAddGoodealController.php
> +  private function cleanValue(array $data): array
clean dead code please

2022-11-09 10:56 UTC, Benja-san commented on src/Model/AddGoodealManager.php
> +/*       $regionId = new RegionManager();
clean dead code

2022-11-09 10:56 UTC, Benja-san commented on src/Model/AuthorManager.php
> + /*   public function selectAuthorById(): int
dead code

2022-11-09 10:56 UTC, Benja-san commented on src/Model/RegionManager.php
> +/*    public function selectRegionById($announcement): int
dead code

2022-11-09 10:56 UTC, Benja-san commented on src/View/Announcement/addGoodeal.html.twig
> +	<div class="form">
main tag required

2022-11-09 10:56 UTC, Benja-san commented on src/View/Announcement/addGoodeal.html.twig
> +				<!-- <label for="category">Choisis ta Catégorie*</label>
dead coee? or use twig syntax for comments

2022-11-09 10:56 UTC, Benja-san commented on src/View/Announcement/addGoodeal.html.twig
> +				<!--<label for="region">Région du GooDeal*</label>
same here

2022-11-09 10:56 UTC, Benja-san commented on src/View/Announcement/addGoodeal.html.twig
> +																												<label for="end-date">Date de fin</label>
big empty space

2022-11-09 10:56 UTC, Benja-san commented on src/Model/AddGoodealManager.php
> +/*    public function update(array $item): bool
clean dead code

2022-11-09 11:42 UTC, cruiser22 commented on src/Controller/AnnouncementController.php
> +       /* $announcementManager = new AnnouncementManager();
done

2022-11-09 11:59 UTC, cruiser22 commented on src/Controller/FormAddGoodealController.php
> +  private function cleanValue(array $data): array
done

2022-11-09 12:00 UTC, cruiser22 commented on src/Model/AddGoodealManager.php
> +/*       $regionId = new RegionManager();
ok

2022-11-09 12:01 UTC, cruiser22 commented on src/Model/AuthorManager.php
> + /*   public function selectAuthorById(): int
done

2022-11-09 12:02 UTC, cruiser22 commented on src/Model/RegionManager.php
> +/*    public function selectRegionById($announcement): int
done

2022-11-09 12:04 UTC, cruiser22 commented on src/View/Announcement/addGoodeal.html.twig
> +	<div class="form">
done

2022-11-09 12:05 UTC, cruiser22 commented on src/View/Announcement/addGoodeal.html.twig
> +				<!-- <label for="category">Choisis ta Catégorie*</label>
done

2022-11-09 12:05 UTC, cruiser22 commented on src/View/Announcement/addGoodeal.html.twig
> +				<!--<label for="region">Région du GooDeal*</label>
done

2022-11-09 12:08 UTC, cruiser22 commented on src/View/Announcement/addGoodeal.html.twig
> +																												<label for="end-date">Date de fin</label>
done

2022-11-09 12:43 UTC, Benja-san approved these changes

2022-11-09 12:54 UTC, merged