markup for one cart created;
WildCodeSchool/goodealmaps pull request #3
Opened 2022-10-24 07:21 UTC by Kengaroo

Version desktop

2022-10-24 07:24 UTC, Kengaroo commented
Single cart design (desktop)

2022-10-24 09:12 UTC, Feals requested changes
In _cart.html.twig 
line 4 write src="assets/images/icons/Edit.svg" no src="assets/images/icons/edit.svg"
line 7 write src="assets/images/icons/Remove.png" no src="assets/images/icons/remove.png"
line 14 change class name to something like "cart-date-city" and change CSS in function
line 15 delete tag span

2022-10-24 09:15 UTC, Feals requested changes
category.html.twig 
delete block header if not we will have a empty header

2022-10-24 09:17 UTC, Feals requested changes
ask to merge on dev branch, not main

2022-11-07 11:33 UTC, AlexMouth approved these changes

2022-11-08 08:55 UTC, Benja-san requested changes

2022-11-08 08:55 UTC, Benja-san commented on src/Controller/AnnouncementController.php
> +    public function selectCard(int $id): string
better call this method "show" for coherence

2022-11-08 08:55 UTC, Benja-san commented on src/View/Announcement/card.html.twig
> +{% extends 'layout.html.twig' %}
could you recall this file "detail" ?

2022-11-08 10:19 UTC, Benja-san approved these changes

2022-11-08 10:40 UTC, Feals approved these changes

2022-11-08 10:41 UTC, merged